# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 2SR1bFkgvJ6UDLAUXVHIeKkxwdzjbdxA
            client-secret: Nad6lpT6t7M2Xdbp4Y31sfjpNvR6UEMaoJ6vPGVfsz3SAkBX4FO8TEP92ZrbxQ7m
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-o6ofwtae.us.auth0.com/
